// Datos de ejemplo de la clase y configuración del reproductor.
// Esto debería generarse a partir de llamadas al API.
class PlayerData {
  /// Datos de la clase
  static final data = {
    "title": "Bestcycling 31 - Lucía De Santos",
    "trainer": "Lucía De Santos",
    "progression": [
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Baja",
        "rpm": "90-98",
        "startOfInterval": false,
        "timeString": "00:00:00",
        "zone": 0.8,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Media-Baja",
        "rpm": "98-64",
        "startOfInterval": false,
        "timeString": "03:23:00",
        "zone": 0.99,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "De pie",
        "resistance": "Media-Baja",
        "rpm": "64",
        "startOfInterval": false,
        "timeString": "03:57:00",
        "zone": 1.19,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Media-Baja",
        "rpm": "64-65",
        "startOfInterval": false,
        "timeString": "04:27:00",
        "zone": 1.15,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "De pie",
        "resistance": "Media-Baja",
        "rpm": "65-67",
        "startOfInterval": false,
        "timeString": "04:56:00",
        "zone": 1.67,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Media-Baja",
        "rpm": "67",
        "startOfInterval": false,
        "timeString": "06:08:00",
        "zone": 1.39,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "De Pie",
        "resistance": "Media-Baja",
        "rpm": "67-68",
        "startOfInterval": false,
        "timeString": "06:52:00",
        "zone": 1.6399999999999997,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Media-Baja",
        "rpm": "68",
        "startOfInterval": false,
        "timeString": "08:26:00",
        "zone": 1.42,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "De Pie",
        "resistance": "Media-Baja",
        "rpm": "68",
        "startOfInterval": false,
        "timeString": "08:52:00",
        "zone": 1.5099999999999998,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Media-Baja",
        "rpm": "68",
        "startOfInterval": false,
        "timeString": "09:16:00",
        "zone": 1.5499999999999998,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "De pie",
        "resistance": "Media-Baja",
        "rpm": "68-69",
        "startOfInterval": false,
        "timeString": "09:30:00",
        "zone": 1.6600000000000001,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Media",
        "rpm": "69-70",
        "startOfInterval": false,
        "timeString": "10:12:00",
        "zone": 1.83,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "De Pie",
        "resistance": "Media",
        "rpm": "70-74",
        "startOfInterval": false,
        "timeString": "10:53:00",
        "zone": 2.3,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Baja",
        "rpm": "74-98",
        "startOfInterval": false,
        "timeString": "11:32:00",
        "zone": 1.03,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Media-Baja",
        "rpm": "98-64",
        "startOfInterval": false,
        "timeString": "13:19:00",
        "zone": 1.35,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "De pie",
        "resistance": "Media-Baja",
        "rpm": "64-65",
        "startOfInterval": false,
        "timeString": "14:44:00",
        "zone": 1.7999999999999998,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Media-Baja",
        "rpm": "65-66",
        "startOfInterval": false,
        "timeString": "16:05:00",
        "zone": 1.5499999999999998,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "De pie",
        "resistance": "Media-Baja",
        "rpm": "66",
        "startOfInterval": false,
        "timeString": "16:34:00",
        "zone": 1.96,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Media-Baja",
        "rpm": "66",
        "startOfInterval": false,
        "timeString": "17:32:00",
        "zone": 1.58,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Media",
        "rpm": "66-67",
        "startOfInterval": false,
        "timeString": "18:16:00",
        "zone": 1.7400000000000002,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "De pie",
        "resistance": "Media",
        "rpm": "67-65",
        "startOfInterval": false,
        "timeString": "18:59:00",
        "zone": 2.46,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Media-Baja",
        "rpm": "65-63",
        "startOfInterval": false,
        "timeString": "19:56:00",
        "zone": 1.42,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "De pie",
        "resistance": "Media-Baja",
        "rpm": "63-64",
        "startOfInterval": false,
        "timeString": "21:13:00",
        "zone": 1.7999999999999998,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Media",
        "rpm": "64-67",
        "startOfInterval": false,
        "timeString": "21:59:00",
        "zone": 1.9500000000000002,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "De pie",
        "resistance": "Media",
        "rpm": "67",
        "startOfInterval": false,
        "timeString": "22:41:00",
        "zone": 2.27,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Media-Alta",
        "rpm": "67-70",
        "startOfInterval": false,
        "timeString": "23:16:00",
        "zone": 2.52,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "De pie",
        "resistance": "Media-Alta",
        "rpm": "70-72",
        "startOfInterval": false,
        "timeString": "23:39:00",
        "zone": 2.86,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Media-Baja",
        "rpm": "65-67",
        "startOfInterval": false,
        "timeString": "24:32:00",
        "zone": 1.35,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Media-Baja",
        "rpm": "67",
        "startOfInterval": false,
        "timeString": "25:30:00",
        "zone": 1.62,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "De pie",
        "resistance": "Media-Baja",
        "rpm": "67",
        "startOfInterval": false,
        "timeString": "25:44:00",
        "zone": 2.09,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Media",
        "rpm": "67",
        "startOfInterval": false,
        "timeString": "26:41:00",
        "zone": 1.94,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "De pie",
        "resistance": "Media",
        "rpm": "67-69",
        "startOfInterval": false,
        "timeString": "27:09:00",
        "zone": 2.35,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Media",
        "rpm": "69",
        "startOfInterval": false,
        "timeString": "29:29:00",
        "zone": 2.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "De Pie",
        "resistance": "Media",
        "rpm": "69-71",
        "startOfInterval": false,
        "timeString": "29:36:00",
        "zone": 2.72,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Media",
        "rpm": "71",
        "startOfInterval": false,
        "timeString": "30:03:00",
        "zone": 2.35,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Media-Alta",
        "rpm": "71-72",
        "startOfInterval": false,
        "timeString": "30:56:00",
        "zone": 2.81,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "De Pie",
        "resistance": "Media-Alta",
        "rpm": "72",
        "startOfInterval": false,
        "timeString": "31:10:00",
        "zone": 3.4,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Media",
        "rpm": "72-66",
        "startOfInterval": false,
        "timeString": "32:42:00",
        "zone": 1.63,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "De Pie",
        "resistance": "Media",
        "rpm": "66",
        "startOfInterval": false,
        "timeString": "34:35:00",
        "zone": 2.14,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Media-Alta",
        "rpm": "66",
        "startOfInterval": false,
        "timeString": "35:04:00",
        "zone": 2.63,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "De pie",
        "resistance": "Media-Alta",
        "rpm": "66-63",
        "startOfInterval": false,
        "timeString": "35:33:00",
        "zone": 3.13,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Media",
        "rpm": "63-64",
        "startOfInterval": false,
        "timeString": "36:16:00",
        "zone": 2.68,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Media-Alta",
        "rpm": "65",
        "startOfInterval": false,
        "timeString": "38:08:00",
        "zone": 3.1,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "De pie",
        "resistance": "Media-Alta",
        "rpm": "64-77",
        "startOfInterval": false,
        "timeString": "38:14:00",
        "zone": 3.67,
      },
      {
        "block": "Bloque 1",
        "endOfInterval": false,
        "method": "Vuelta a la calma",
        "resistance": "Baja",
        "rpm": "77-104",
        "startOfInterval": false,
        "timeString": "40:01:00",
        "zone": 0.8181818181818181,
      },
      {
        "block": "Bloque 1",
        "endOfInterval": false,
        "method": "Estiramientos",
        "resistance": "Muy suave",
        "rpm": "104",
        "startOfInterval": false,
        "timeString": "42:52:00",
        "zone": 0.0,
      },
      {
        "block": "Bloque 1",
        "endOfInterval": false,
        "method": "",
        "resistance": "Baja",
        "rpm": "65",
        "startOfInterval": false,
        "timeString": "50:13:00",
        "zone": 0.0,
      },
    ],
    "progression_watts": [
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Muy suave",
        "rpm": "90-98",
        "startOfInterval": false,
        "timeString": "00:00:00",
        "zone": 1.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Suave",
        "rpm": "98-64",
        "startOfInterval": false,
        "timeString": "03:23:00",
        "zone": 1.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "De pie",
        "resistance": "Suave",
        "rpm": "64",
        "startOfInterval": false,
        "timeString": "03:57:00",
        "zone": 1.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Suave",
        "rpm": "64-65",
        "startOfInterval": false,
        "timeString": "04:27:00",
        "zone": 1.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "De pie",
        "resistance": "Suave",
        "rpm": "65-67",
        "startOfInterval": false,
        "timeString": "04:56:00",
        "zone": 1.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Suave",
        "rpm": "67",
        "startOfInterval": false,
        "timeString": "06:08:00",
        "zone": 1.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "De Pie",
        "resistance": "Suave",
        "rpm": "67-68",
        "startOfInterval": false,
        "timeString": "06:52:00",
        "zone": 1.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Suave",
        "rpm": "68",
        "startOfInterval": false,
        "timeString": "08:26:00",
        "zone": 1.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "De Pie",
        "resistance": "Suave",
        "rpm": "68",
        "startOfInterval": false,
        "timeString": "08:52:00",
        "zone": 1.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Suave",
        "rpm": "68",
        "startOfInterval": false,
        "timeString": "09:16:00",
        "zone": 1.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "De pie",
        "resistance": "Suave",
        "rpm": "68-69",
        "startOfInterval": false,
        "timeString": "09:30:00",
        "zone": 2.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Medio",
        "rpm": "69-70",
        "startOfInterval": false,
        "timeString": "10:12:00",
        "zone": 2.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "De Pie",
        "resistance": "Medio",
        "rpm": "70-74",
        "startOfInterval": false,
        "timeString": "10:53:00",
        "zone": 0.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Muy suave",
        "rpm": "74-98",
        "startOfInterval": false,
        "timeString": "11:32:00",
        "zone": 1.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Suave",
        "rpm": "98-64",
        "startOfInterval": false,
        "timeString": "13:19:00",
        "zone": 1.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "De pie",
        "resistance": "Suave",
        "rpm": "64-65",
        "startOfInterval": false,
        "timeString": "14:44:00",
        "zone": 1.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Suave",
        "rpm": "65-66",
        "startOfInterval": false,
        "timeString": "16:05:00",
        "zone": 1.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "De pie",
        "resistance": "Suave",
        "rpm": "66",
        "startOfInterval": false,
        "timeString": "16:34:00",
        "zone": 1.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Suave",
        "rpm": "66",
        "startOfInterval": false,
        "timeString": "17:32:00",
        "zone": 2.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Medio",
        "rpm": "66-67",
        "startOfInterval": false,
        "timeString": "18:16:00",
        "zone": 2.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "De pie",
        "resistance": "Medio",
        "rpm": "67-65",
        "startOfInterval": false,
        "timeString": "18:59:00",
        "zone": 1.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Medio",
        "rpm": "65-63",
        "startOfInterval": false,
        "timeString": "19:56:00",
        "zone": 1.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "De pie",
        "resistance": "Medio",
        "rpm": "63-64",
        "startOfInterval": false,
        "timeString": "21:13:00",
        "zone": 2.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Medio",
        "rpm": "64-67",
        "startOfInterval": false,
        "timeString": "21:59:00",
        "zone": 2.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "De pie",
        "resistance": "Medio",
        "rpm": "67",
        "startOfInterval": false,
        "timeString": "22:41:00",
        "zone": 3.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Muy Ligero",
        "rpm": "67-69",
        "startOfInterval": false,
        "timeString": "23:11:00",
        "zone": 3.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "De pie",
        "resistance": "Muy Ligero",
        "rpm": "70-72",
        "startOfInterval": false,
        "timeString": "23:39:00",
        "zone": 1.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Suave",
        "rpm": "72-67",
        "startOfInterval": false,
        "timeString": "24:32:00",
        "zone": 1.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Medio",
        "rpm": "67",
        "startOfInterval": false,
        "timeString": "25:30:00",
        "zone": 1.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "De pie",
        "resistance": "Medio",
        "rpm": "67",
        "startOfInterval": false,
        "timeString": "25:44:00",
        "zone": 2.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Medio",
        "rpm": "67",
        "startOfInterval": false,
        "timeString": "26:41:00",
        "zone": 2.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "De pie",
        "resistance": "Medio",
        "rpm": "67-69",
        "startOfInterval": false,
        "timeString": "27:09:00",
        "zone": 2.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Intenso",
        "rpm": "69",
        "startOfInterval": false,
        "timeString": "29:29:00",
        "zone": 2.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "De Pie",
        "resistance": "Intenso",
        "rpm": "69-71",
        "startOfInterval": false,
        "timeString": "29:36:00",
        "zone": 2.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Medio",
        "rpm": "71",
        "startOfInterval": false,
        "timeString": "30:03:00",
        "zone": 3.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Intenso",
        "rpm": "71-72",
        "startOfInterval": false,
        "timeString": "30:56:00",
        "zone": 3.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "De Pie",
        "resistance": "Intenso",
        "rpm": "72-75",
        "startOfInterval": false,
        "timeString": "31:10:00",
        "zone": 2.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Suave",
        "rpm": "65-66",
        "startOfInterval": false,
        "timeString": "32:42:00",
        "zone": 2.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "De Pie",
        "resistance": "Medio",
        "rpm": "66",
        "startOfInterval": false,
        "timeString": "34:35:00",
        "zone": 3.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Intenso",
        "rpm": "66",
        "startOfInterval": false,
        "timeString": "35:04:00",
        "zone": 3.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "De pie",
        "resistance": "Intenso",
        "rpm": "66-63",
        "startOfInterval": false,
        "timeString": "35:33:00",
        "zone": 2.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Intenso",
        "rpm": "63-64",
        "startOfInterval": false,
        "timeString": "36:16:00",
        "zone": 3.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Muy Ligero",
        "rpm": "65",
        "startOfInterval": false,
        "timeString": "38:01:00",
        "zone": 3.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "De pie",
        "resistance": "Intenso",
        "rpm": "64-75",
        "startOfInterval": false,
        "timeString": "38:14:00",
        "zone": 4.5,
      },
      {
        "block": "",
        "endOfInterval": false,
        "method": "Sentado",
        "resistance": "Muy Ligero",
        "rpm": "75-77",
        "startOfInterval": false,
        "timeString": "39:11:00",
        "zone": 0.5,
      },
      {
        "block": "Bloque 1",
        "endOfInterval": false,
        "method": "Vuelta a la calma",
        "resistance": "Muy suave",
        "rpm": "77-104",
        "startOfInterval": false,
        "timeString": "40:01:00",
        "zone": 0.5,
      },
      {
        "block": "Bloque 1",
        "endOfInterval": false,
        "method": "Estiramientos",
        "resistance": "Muy suave",
        "rpm": "104",
        "startOfInterval": false,
        "timeString": "42:52:00",
        "zone": 0.5,
      },
      {
        "block": "Bloque 1",
        "endOfInterval": false,
        "method": "",
        "resistance": "Baja",
        "rpm": "65",
        "startOfInterval": false,
        "timeString": "50:13:00",
        "zone": 0.0,
      },
    ],
    "delay_seconds": -58,
    "duration_seconds": 2876,
    "duration_training": 2572,
    "official": true,
    "url":
        "https://apiv2.bestcycling.es/api/v2/media_assets/288902/?type=video_hd",
    "isNew": true,
    "hasBackground": true,
    "isNewBlack": true,
    "category": 1,
    "show_effort": true,
    "need_progression": true,
    "mediaType": "video",
    "image_graph":
        "https://cdn0.bestcycling.es/image_covers/images/000/302/253/l.png?1626176648",
    "gender": "m",
    "age": 39,
    "weight": 72.0,
  };

  /// Preferencias de usuario
  static final preferences = {
    "video": {
      "video_theme": "theme-bestangular",
      "video_theme_name": "Rectángulos",
      "showmonitor_centered": true,
      "show_intro_video": true,
      "showinfo_video_effects": true,
      "show_planner_intro_video": false,
      "vista_monitor": false,
      "showinfo_rpm": true,
      "showinfo_resistance": true,
      "showinfo_timeto": true,
      "showinfo_zone": true,
      "showinfo_method_description": true,
      "showinfo_method": true,
      "resume_view": true,
      "showinfo_logo": true,
      "show_end_of_interval": false,
      "logo": "",
    },
    "graph": {
      "zone_color_5": "#f13b46",
      "zone_color_4": "#ff7900",
      "zone_color_3": "#fcd900",
      "zone_color_2": "#69ae00",
      "zone_color_1": "#0098c3",
      "zoom_graph": false,
      "preferred_graph_type": "fc",
      "heart_rate_box_height_percentage": 0.3,
    },
    "cardio": {
      "mode": "fcb",
      "enabled": false,
      "external": true,
      "fcm": 120,
      "fcb": 100,
      "fcr": 20,
      "customPPM": null,
    },
    "ftms": {
      "enabled": false,
      "ftp": 253,
      "features": {
        "RESISTENCE_LEVEL_RANGE": false,
        "Nivel de resistencia": false,
        "Cadencia": false,
        "Potencia": false,
        "Velocidad media": false,
        "Potencia objetivo": false,
        "Resistencia objetivo": false,
        "Control manual de botones": false,
      },
      "resistance_level_range": null,
      "autoMode": true,
    },
    "range": {
      "show_range": true,
      "condition": 1,
      "custom_range": false,
      "custom_range_bottom": 60,
      "custom_range_top": 96,
      "custom_range_bottom_percent": 0.5,
      "custom_range_top_percent": 0.5,
    },
    "running": {
      "showVelocity": false,
      "show_velocity": false,
      "show_graph": true,
    },
    "is_tablet": false,
  };
}
